### ISSUE TITLE
PostSharp+Metalama extension prevents VS from showing mouse-over tooltips in a Unity generated solution.

### ISSUE THREAD

**Issue by XtroTheArctic** [metalama/Metalama#336]
Here is the video of the problem.

https://drive.google.com/file/d/1_Ua_isGaRfHdAlOQWwy1LnM6O-80qp53/view?usp=sharing

**Comment by gfraiteur** [comment]
Thank you for reporting the issue.

**Comment by gfraiteur** [comment]
Fixed in 2025.0.8.

**Comment by XtroTheArctic** [comment]
Happy new year @gfraiteur. It's been so long since you shut down the Slack server. I hope everything is going well on your side.

On the other hand, this ticket is still an issue in 2026.0.12.

I have been seriously busy with my game project for very long time so, I neglected keeping my software updated (VS2022, Resharper, Metalama...).

Recently, I installed VS2026. While applying my VS2022 settings to it, I noticed that the Metalama plugin version which I have installed was 2024.1.24 and it was in disabled state. I didn't remember why it was disabled until I experience this tooltip problem once again in VS2026.

Since I never updated Metalama from 2024.1.24 to 2025.0.8, I can't confirm this problem was ever fixed but it definitely is still there in  2026.0.12 so I have to keep it in disabled state again :(

Can you please check this again?

**Comment by gfraiteur** [comment]
Hi Onur, happy new year to you too. Could you put the video online again?

**Comment by XtroTheArctic** [comment]
Hi Gael.

Here is the new video with VS2026 and Metalama Extension 2026.0.12.
https://drive.google.com/file/d/1bB7CA-yZnNjXUbb6jzHI8DRDOxG7OKNF/view?usp=drive_link

While recording this, I noticed ANOTHER problem which is kind of major. I'll explain below.

Also, I forgot to stop my music while recording so... I hope you enjoy the music too 😆 

One more thing... My video recorder (Nvidia App) doesn't capture VS's mouse text caret while it's over the text editor. When you don't see the caret, it means I'm keeping it over multiple C# symbols in the code but the tooltip doesn't work.

1. The video starts right after I install Metalama and start VS first time after.
2. Tooltip doesn't work as I mouse over the C# symbols (mouse caret isn't recorded)
3. 00:13 : I open Extensions menu and Metalama option is visible.
4. 00:29 : I disable Metalama and close VS.
5. 00:44 : I start VS with a wrong project. Please ignore this.
6. 01:03 : I started VS with the correct project where Metalama is disabled now.
7. 01:09 : Metalama option is not in Extension menu anymore.
8. 01:18 : After VS and Resharper finishes their initialization, tooltip starts working.
9. 01:32 : I enable Metalama and close VS.
10. 01: 56 : I start VS but Metalama is not in Extensions menu even after I enabled it. This is the new major problem I mentioned above.
11. 02:06 : Tooltip works when Metalama is enabled but Metalama is not active actually as mentioned in step 10 above.
12. 02:27 : One more time, I show that Metalama is enabled in extension manager but not visible in Extension menu.
13. 02:35 : I disable Metalama and close VS.
14. 03:09 : After VS and Resharper finishes their initialization, tooltip works fine.
15. 03:22 : I uninstall Metalama and close VS.
16. 04:07 : After VS and Resharper finishes their initialization, tooltip works fine.
17. 04:23 : In install Metalama again and start VS. (Just as I did before starting this video)
18. 04:56 : There is the Metalama warning about my project at the top of the screen because Metalama is actually active now after the installation. The warning wasn't there after I enabled Metalama in step 10 above because it's not in active state actually.
19. 05:03 : Metalama is back in Extension menu.
20. 05:12 : Tooltips don't work anymore because Metalama is enabled and really active.

**Comment by XtroTheArctic** [comment]
@gfraiteur Were you able to check this?

In short, "enable" doesn't enable Metalama after it was disabled.

**Comment by gfraiteur** [comment]
I didn't look at it. I can't prioritize this now.

**Comment by conormcg94** [comment]
Hi Gael, I've encountered as well with Metalama VS extension 2026.0.12 and VS 18.6.2.
Metalama seems to kill the informational tooltips as well as compile errors. When I hover over red compiler errors, the description does not pop-up, this makes for a frustrating experience and so I've had to disable the extension.
